One click
MoveOnOrg/python-actionkit pull request #26
Opened 2019-06-19 14:38 UTC by nilatti

@schuyler1d 
This goes with Asana task https://app.asana.com/0/153988187951298/933603975155761

2019-06-20 21:56 UTC, schuyler1d requested changes
Hey sorry, forgot to hit submit here.

Basically: functions good, DB and moveon-specific code let's move elsewhere after a plan

2019-06-20 21:56 UTC, schuyler1d commented on actionkit/utils.py
> +import psycopg2
This is a library file (and is imported in many projects for the methods here)
So: please remove the `psycopg2` and `settings` imports here.  `settings` can be passed as an argument to the methods here -- or even better, just pass the variables necessary into the abstract methods in this file.

2019-06-20 21:56 UTC, schuyler1d commented on actionkit/utils.py
> +def generate_token_id(user_id):
Let's remove this method from the library and move this to a separate repo for the 'application' -- probably something we should understand at an Architecture level before committing to e.g. doing a SQL call per-userid.  This is a good prototype demonstrating feasibility, though.

2019-06-20 21:56 UTC, schuyler1d commented on actionkit/utils.py
> +    return 'https://act.moveon.org/donate/civ-donation-quickpay?payment_hash=' + payment_hash(token_id, datetime_format, braintree_secret, hash_separator) + '&akid=' + akid
This library should not assume MoveOn urls, so `page_url` could be an argument or we could just remove the function here, and, again, wait for a planned architecture and application

2019-06-20 21:56 UTC, schuyler1d commented on actionkit/quickpay_url_generator.py
> +print(get_array_of_payment_urls(['18715613', '8934025', '7666955']))
Better to do the `if __name__ == '__main__'` thing here, too -- or even just remove

2019-06-20 21:56 UTC, schuyler1d commented on actionkit/test_quickpay_url_generator.py
> +        self.token_id = '3nmqoul2'
Just making sure this isn't a real token secret?

2019-06-20 21:56 UTC, schuyler1d commented on actionkit/test_quickpay_url_generator.py
> +        self.assertIn("&akid=.18715613", url)
would be good to add a test that it matches `.18715613.\w{6}`

2019-06-20 21:56 UTC, schuyler1d commented on actionkit/test_quickpay_url_generator.py
> +        self.braintree_secret = settings.BRAINTREE_ONECLICK_SECRET
This is a test, so let's set the values to junk plausible ones and then verify the actual hashes generated to ensure the algorithm 'works' as expected.

2019-06-21 01:35 UTC, nilatti commented on actionkit/test_quickpay_url_generator.py
> +        self.token_id = '3nmqoul2'
It's mine--I didn't know how to generate a fake one. I felt like it was okay for this proof of concept phase, but not to go beyond that.

2019-06-21 01:36 UTC, nilatti commented on actionkit/utils.py
> +def generate_token_id(user_id):
I agree with this and several of your other comments that are similar. I wasn't exactly sure how the architecture would work ultimately. This whole thing is a very prototypey prototype. Let's connect about what the next phase should look like, architecturally.

2019-06-21 01:36 UTC, nilatti commented on actionkit/test_quickpay_url_generator.py
> +        self.braintree_secret = settings.BRAINTREE_ONECLICK_SECRET
Do you have documentation about what would make them plausible enough to pass?

2020-12-01 18:11 UTC, closed without merging